### PR TITLE
Update to remove deprecated shapely behaviours (#2)

### PR DESCRIPTION
**Pull request by connorferster**
In reference to #2. Also created a basic test and added pytest to the setup.py (dev) requirements.

This pull request is in preparation of releasing sectionproperties v2

### CODE REVIEW

**Comment by aegis1980** [comment]
Hey. Will check out as soon as the sun stops shining (New Zealand shuts down over summer/Christmas). 
Keen to breathe some life into this repo too.

**Comment by connorferster** [comment]
Heyo @aegis1980! It looks like Robbie is getting ready to release v2 of sectionproperties within a week. Would you have time to review this PR in the next few days? Would be great to have this dependency up-to-date on PyPI when it launches :)

**Comment by aegis1980** [comment]
Hey,
I think I have okayed, released and everything else? Bit rusty on it all.
Am sure your contribution significantly more considered than my original
stuff - i don't really get the opportunity to write much code these days.
Jon

**Comment by connorferster** [comment]
Thanks so much! If it's updated on PyPI then that should fix the error messages we see in the built sectionproperties docs.

**Comment by aegis1980** [comment]
Hummmmm, I'm getting a build error for pypi release github action. Grrrr!

Friday evening here and sun is out....
So will fix over weekend!

**Comment by robbievanleeuwen** [comment]
You might need to update the version in `setup.py` which is still displaying 0.1.9 and then create a new github release tag?

**Comment by aegis1980** [comment]
Cool. Thanks. That was it.
Done.

**Pull request merged**
